In [1]:
import tensorflow as tf

In [2]:
import pandas as pd

In [3]:
rank_0_tensor = tf.constant(1)

In [4]:
print(rank_0_tensor)

tf.Tensor(1, shape=(), dtype=int32)


In [5]:
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
rank_1_tensor = tf.constant([1, 2, 3, 4, 5])

In [7]:
rank_1_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [8]:
print(rank_1_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [9]:
rank_2_tensor = tf.constant([[1, 2, 3, 4], [1.0, 2.0, 3.0, 4.0]])

In [10]:
rank_2_tensor

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [1., 2., 3., 4.]], dtype=float32)>

In [11]:
print(rank_2_tensor)

tf.Tensor(
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]], shape=(2, 4), dtype=float32)


In [12]:
rank_3_tensor = tf.constant([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

In [13]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])>

In [14]:
print(rank_3_tensor)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)


In [15]:
import numpy as np

In [16]:
rank_3_tensor_as_numpy = np.array(rank_3_tensor)

In [17]:
rank_3_tensor_as_numpy

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [18]:
print(rank_3_tensor_as_numpy)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [19]:
rank_3_tensor_as_numpy_1 = rank_3_tensor.numpy()

In [20]:
rank_3_tensor_as_numpy_1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [21]:
print(rank_3_tensor_as_numpy_1)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [22]:
tf1 = tf.constant([[1, 2, 3], [4, 5, 6]])

In [23]:
tf2 = tf.constant([[4, 5, 6], [7, 8, 9]])

In [24]:
tf1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [25]:
tf2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]])>

In [26]:
tf_add = tf.add(tf1, tf2)

In [27]:
tf_add

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  7,  9],
       [11, 13, 15]])>

In [28]:
tf_mul = tf.multiply(tf1, tf2)

In [29]:
tf_mul

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 10, 18],
       [28, 40, 54]])>

In [30]:
tf1 + tf2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  7,  9],
       [11, 13, 15]])>

In [31]:
tf1 * tf2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 10, 18],
       [28, 40, 54]])>

In [32]:
tf.matmul(tf1, tf.ones([3, 2], dtype=tf.int32))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  6],
       [15, 15]])>

In [33]:
tf1 @ tf.ones([3, 2], dtype = tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  6],
       [15, 15]])>