<h1 color="Blue">TensorFlow Basic</h1>

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
rank_0_tensor = tf.constant(4) #this is a scalar tensor with single value and no axis. Tensor are immutable once create we can't update

In [4]:
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [5]:
rank_1_tensor =  tf.constant([1, 2, 3, 4, 5]) # Kind of List

In [6]:
rank_1_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [7]:
rank_1_tensor_1 = tf.constant([1.0, 2, 3.0, 4.41]) #the dtype will be same for all the values and if possible they will be casted accordingy 

In [8]:
rank_1_tensor_1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.  , 2.  , 3.  , 4.41], dtype=float32)>

In [9]:
rank_1_tensor_1.shape

TensorShape([4])

In [10]:
#rank_1_tensor_2 = tf.constant([1, 2.0, 3.14, "MY", "NAME", "IS", "DEEPAK"])  #what will happen if i run this as dtype is
# different here we will run into error 

In [11]:
rank_2_tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
rank_2_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [13]:
rank_3_tensor = tf.constant([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9,], [10, 11, 12]]], dtype=np.int32)

In [14]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

<h1>Convert Tensor to Numpy Array's</h1>

In [15]:
rank_3_numpy_array = np.array(rank_3_tensor)

In [16]:
rank_3_numpy_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
type(rank_3_numpy_array)

numpy.ndarray

In [18]:
rank_3_numpy_array_1 = rank_3_tensor.numpy()

In [19]:
rank_3_numpy_array_1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
type(rank_3_numpy_array_1)

numpy.ndarray

In [21]:
tensor1 = tf.constant([[1, 2, 3, 4],[5, 6, 7, 8]])

In [22]:
tensor2 = tf.constant([[1, 2, 3, 4],[5, 6, 7, 8]])

In [23]:
tf.add(tensor1, tensor2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])>

In [24]:
tf.multiply(tensor1, tensor2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])>

In [25]:
tf.matmul(tensor1, tf.ones([4,4], dtype=tf.int32))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [26, 26, 26, 26]])>

In [26]:
#simple methods

In [27]:
tensor1 + tensor2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])>

In [28]:
tensor1 * tensor2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])>

In [29]:
tensor1 @ tf.ones([4,2], dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [26, 26]])>

# Some Function

In [ ]:
# Find the largest value
tf.reduce_max(tensor1)

In [ ]:
tf.reduce_min(tensor1)

In [ ]:
tf.reduce_mean(tensor1)

In [ ]:
tf.reduce_sum(tensor1)

In [ ]:
tf.argmax(tensor1)

In [ ]:
tf.argmax(rank_1_tensor)

In [ ]:
tf.argmax(rank_3_tensor)

In [ ]:
rank_4_tensor = np.zeros([3, 2, 4, 4])

In [ ]:
rank_4_tensor

In [ ]:
rank_4_tensor.shape

In [ ]:
rank_4_tensor.ndim

In [ ]:
rank_4_tensor.dtype

In [ ]:
rank_4_tensor.size

In [ ]:
rank_4_tensor.shape[0]

In [ ]:
rank_4_tensor.shape[-1]

## Indexing 

# For indexing the syntax is [Start : End: Steps]

In [ ]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

In [ ]:
rank_1_tensor[0]

In [ ]:
rank_1_tensor[1]

In [ ]:
rank_1_tensor[:]

In [ ]:
rank_1_tensor[:2]

In [ ]:
rank_1_tensor[::2]

In [ ]:
rank_1_tensor[:-1]

In [ ]:
rank_1_tensor[-1:-8:-1]

In [ ]:
rank_1_tensor[::-1]

for multi-dimensional tensor the indexing is same as 1d Tensor with just a , in between [start:end, start:end]

In [ ]:
rank_2_tensor

In [ ]:
rank_2_tensor[::,::]

In [ ]:
rank_2_tensor[0, :]

In [ ]:
rank_2_tensor[1, :]

In [ ]:
rank_2_tensor[2, :]

In [ ]:
rank_2_tensor[:2]

In [ ]:
rank_2_tensor[:2, :]

In [ ]:
rank_2_tensor[:2, :1]

In [ ]:
rank_2_tensor[-1, 0]

In [ ]:
rank_2_tensor[0, -1]

In [ ]:
rank_3_tensor

In [ ]:
rank_3_tensor[0, 0, :]

In [ ]:
rank_3_tensor[:, 0, :]

# Manipulation Shapes 

In [ ]:
a = tf.constant([[1], [2], [3]])

In [ ]:
a.shape

In [ ]:
a.shape.as_list()

In [ ]:
tf.reshape(a, [1, 3])

In [ ]:
rank_2_tensor

In [ ]:
rank_3_tensor

In [ ]:
#to flatten any tensor we use shape = [-1]
tf.reshape(rank_3_tensor, shape=[-1])

In [ ]:
rank_3_tensor

In [ ]:
tf.reshape(rank_2_tensor, shape=[-1]) #and in this way data is stored in memory

In [ ]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

In [ ]:
rank_3_tensor

In [ ]:
tf.reshape(rank_3_tensor, shape=[-1])

In [ ]:
tf.reshape(rank_3_tensor, shape=[3,1,10])

In [ ]:
tf.reshape(rank_3_tensor, shape=[3,5,2])

In [ ]:
tf.reshape(rank_3_tensor, shape=[6,5])

In [ ]:
tf.reshape(rank_3_tensor, shape=[30])

In [ ]:
rank_3_tensor.shape

In [ ]:
rank_3_tensor

In [ ]:
tf.reshape(rank_3_tensor, [5, 2, 3])

In [ ]:
rank_1_tensor.dtype

In [ ]:
tf.cast(rank_1_tensor, dtype=tf.int8)

# Broadcasting

In [ ]:
#The smaller tensor are sometime broadcasted to match the size

In [ ]:
a = tf.constant([2])

In [ ]:
a

In [ ]:
b = tf.constant(2)

In [ ]:
b

In [ ]:
c = tf.constant([1, 2, 3])

In [ ]:
d = tf.constant([2, 2, 2])

In [ ]:
a * b

In [ ]:
a * c

In [ ]:
a * c

In [ ]:
a * d

In [ ]:
b * c

In [ ]:
b * d

In [ ]:
c * d

In [ ]:
#Ragged Tensor

In [ ]:
tf.ragged.constant([[1,2,3,4],[1,2,3],[1,2],[1]]).shape

In [ ]:
#The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the dimensions of the tensor. See tf.strings for functions to manipulate them.
#Here is a scalar string tensor:

In [ ]:
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

In [ ]:
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])


In [ ]:
tensor_of_strings

In [ ]:
tf.constant("🥳👍")

In [ ]:
tf.strings.split(tf.constant("my name is deepak"), sep=" ")

In [ ]:
z = tf.strings.split(tensor_of_strings, sep=" ")

In [ ]:
z

In [ ]:
z.dtype

In [ ]:
z.shape

In [ ]:
z.shape

In [ ]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

In [ ]:
k =  tf.strings.to_number(tf.strings.split(text, " "))

In [ ]:
k

In [ ]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

In [ ]:
#Sparse tensors

In [ ]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[4, 4])

In [ ]:
sparse_tensor

In [ ]:
print(sparse_tensor)

In [ ]:
print(tf.sparse.to_dense(sparse_tensor))