In [1]:
import tensorflow as tf

# Variables are created and tracked via the tf.Variable class. A tf.Variable represents a tensor whose value can be changed by running ops on it.

In [2]:
# Uncomment to see where your variables get placed (see below)
# tf.debugging.set_log_device_placement(True)

In [3]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])

In [4]:
my_tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [5]:
my_tensor.ndim

2

In [6]:
my_tensor.shape

TensorShape([2, 2])

In [7]:
my_variable = tf.Variable(my_tensor, name="deepak")

In [8]:
my_variable

<tf.Variable 'deepak:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [9]:
my_variable.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

# we cannot assign value once defined for tf.constant and tf.Variable

In [10]:
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

In [11]:
bool_variable.dtype

tf.bool

In [12]:
bool_variable.shape

TensorShape([4])

In [13]:
complex_variable.dtype

tf.complex128

In [14]:
complex_variable.shape

TensorShape([2])

In [15]:
bool_variable

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False,  True])>

In [16]:
complex_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>

In [18]:
tf.reduce_min(my_variable)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [19]:
tf.argmax(my_variable)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

# tf.Variables Can Never Be Reshaped

In [20]:
my_variable

<tf.Variable 'deepak:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [22]:
my_variable + 1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [24]:
my_variable = my_variable + 1