In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
corpus_raw = 'He is the king . The king is royal . She is the royal  queen '

In [3]:
corpus_raw = corpus_raw.lower()

In [4]:
words = []

In [5]:
for word in corpus_raw.split():
    words.append(word)

In [6]:
words

['he',
 'is',
 'the',
 'king',
 '.',
 'the',
 'king',
 'is',
 'royal',
 '.',
 'she',
 'is',
 'the',
 'royal',
 'queen']

In [7]:
words = set(words)

In [8]:
words.remove('.')

In [9]:
words

{'he', 'is', 'king', 'queen', 'royal', 'she', 'the'}

In [10]:
word2int = {}
int2word = {}

In [11]:
for index , word in enumerate(words):
    word2int[word]  = index
    int2word[index] = word

In [12]:
word2int

{'royal': 0, 'king': 1, 'he': 2, 'the': 3, 'queen': 4, 'she': 5, 'is': 6}

In [13]:
int2word

{0: 'royal', 1: 'king', 2: 'he', 3: 'the', 4: 'queen', 5: 'she', 6: 'is'}

In [14]:
raw_sentences = corpus_raw.split('.')

In [15]:
raw_sentences

['he is the king ', ' the king is royal ', ' she is the royal  queen ']

In [16]:
sentences = []
for sentence in raw_sentences:
    sentences.append(sentence.split())

In [17]:
sentences

[['he', 'is', 'the', 'king'],
 ['the', 'king', 'is', 'royal'],
 ['she', 'is', 'the', 'royal', 'queen']]

In [18]:
data = []
WINDOW_SIZE = 2

In [19]:
for sentence in sentences:
    for word_index, word in enumerate(sentence):
        for nb_word in sentence[max(word_index - WINDOW_SIZE, 0) : min(word_index + WINDOW_SIZE, len(sentence)) + 1] :
            if nb_word != word:
                data.append([word, nb_word])

In [20]:
data

[['he', 'is'],
 ['he', 'the'],
 ['is', 'he'],
 ['is', 'the'],
 ['is', 'king'],
 ['the', 'he'],
 ['the', 'is'],
 ['the', 'king'],
 ['king', 'is'],
 ['king', 'the'],
 ['the', 'king'],
 ['the', 'is'],
 ['king', 'the'],
 ['king', 'is'],
 ['king', 'royal'],
 ['is', 'the'],
 ['is', 'king'],
 ['is', 'royal'],
 ['royal', 'king'],
 ['royal', 'is'],
 ['she', 'is'],
 ['she', 'the'],
 ['is', 'she'],
 ['is', 'the'],
 ['is', 'royal'],
 ['the', 'she'],
 ['the', 'is'],
 ['the', 'royal'],
 ['the', 'queen'],
 ['royal', 'is'],
 ['royal', 'the'],
 ['royal', 'queen'],
 ['queen', 'the'],
 ['queen', 'royal']]

In [21]:
def to_one_hot_encode(data_point_index, vocab_size):
    temp = np.zeros(vocab_size)
    temp[data_point_index] = 1
    return temp

In [22]:
x_train = [] # input word
y_train = [] # output word

In [23]:
vocab_size = len(words)
for data_word in data:
    x_train.append(to_one_hot_encode(word2int[data_word[0]], vocab_size))
    y_train.append(to_one_hot_encode(word2int[data_word[1]], vocab_size))

In [24]:
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

In [25]:
x_train

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
 

In [26]:
y_train

array([[0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
 

In [27]:
x_train.shape

(34, 7)

In [28]:
y_train.shape

(34, 7)

In [29]:
x = tf.placeholder(tf.float32, shape=(None, vocab_size))
y_label = tf.placeholder(tf.float32, shape=(None, vocab_size))

In [30]:
vocab_size

7

In [31]:
EMBEDDING_DIM = 5 
W1 = tf.Variable(tf.random_normal([vocab_size, EMBEDDING_DIM]))
b1 = tf.Variable(tf.random_normal([EMBEDDING_DIM])) #bias
hidden_representation = tf.add(tf.matmul(x,W1), b1)

In [32]:
W2 = tf.Variable(tf.random_normal([EMBEDDING_DIM, vocab_size]))
b2 = tf.Variable(tf.random_normal([vocab_size]))
prediction = tf.nn.softmax(tf.add( tf.matmul(hidden_representation, W2), b2))

In [33]:
sess = tf.Session()

In [34]:
init = tf.global_variables_initializer()

In [35]:
sess.run(init)

In [36]:
# define the loss function:
cross_entropy_loss = tf.reduce_mean(-tf.reduce_sum(y_label * tf.log(prediction), reduction_indices=[1]))

In [37]:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy_loss)

In [38]:
n_iters = 10000

In [39]:
for _ in range(n_iters):
    sess.run(train_step, feed_dict={x: x_train, y_label: y_train})
    print('loss is : ', sess.run(cross_entropy_loss, feed_dict={x: x_train, y_label: y_train}))

loss is :  3.9401195
loss is :  3.5913284
loss is :  3.3051152
loss is :  3.0751286
loss is :  2.8900027
loss is :  2.7365632
loss is :  2.6045227
loss is :  2.4877694
loss is :  2.3832817
loss is :  2.2897718
loss is :  2.206753
loss is :  2.133996
loss is :  2.0712159
loss is :  2.0179055
loss is :  1.973285
loss is :  1.9363378
loss is :  1.9059123
loss is :  1.8808376
loss is :  1.8600311
loss is :  1.8425604
loss is :  1.8276682
loss is :  1.8147649
loss is :  1.8034037
loss is :  1.793252
loss is :  1.784063
loss is :  1.775653
loss is :  1.7678837
loss is :  1.7606497
loss is :  1.7538697
loss is :  1.7474791
loss is :  1.7414263
loss is :  1.7356697
loss is :  1.7301753
loss is :  1.7249142
loss is :  1.7198625
loss is :  1.715
loss is :  1.7103097
loss is :  1.7057767
loss is :  1.701388
loss is :  1.6971327
loss is :  1.6930012
loss is :  1.6889846
loss is :  1.6850756
loss is :  1.6812677
loss is :  1.6775546
loss is :  1.673931
loss is :  1.6703922
loss is :  1.6669338
loss

loss is :  1.425418
loss is :  1.4252815
loss is :  1.4251453
loss is :  1.4250095
loss is :  1.4248737
loss is :  1.4247384
loss is :  1.4246032
loss is :  1.4244682
loss is :  1.4243336
loss is :  1.4241992
loss is :  1.4240651
loss is :  1.4239311
loss is :  1.4237976
loss is :  1.4236642
loss is :  1.423531
loss is :  1.423398
loss is :  1.4232652
loss is :  1.4231328
loss is :  1.4230005
loss is :  1.4228684
loss is :  1.4227366
loss is :  1.4226049
loss is :  1.4224734
loss is :  1.4223423
loss is :  1.4222114
loss is :  1.4220805
loss is :  1.4219497
loss is :  1.4218193
loss is :  1.4216892
loss is :  1.4215591
loss is :  1.4214293
loss is :  1.4212995
loss is :  1.4211701
loss is :  1.4210405
loss is :  1.4209114
loss is :  1.4207823
loss is :  1.4206536
loss is :  1.4205248
loss is :  1.4203962
loss is :  1.4202679
loss is :  1.4201397
loss is :  1.4200116
loss is :  1.4198837
loss is :  1.4197559
loss is :  1.4196283
loss is :  1.4195008
loss is :  1.4193734
loss is :  1.419

loss is :  1.3731436
loss is :  1.3730074
loss is :  1.372871
loss is :  1.3727349
loss is :  1.3725989
loss is :  1.372463
loss is :  1.3723271
loss is :  1.3721913
loss is :  1.3720555
loss is :  1.37192
loss is :  1.3717846
loss is :  1.371649
loss is :  1.3715137
loss is :  1.3713785
loss is :  1.3712435
loss is :  1.3711084
loss is :  1.3709735
loss is :  1.3708386
loss is :  1.3707039
loss is :  1.3705693
loss is :  1.3704348
loss is :  1.3703004
loss is :  1.3701663
loss is :  1.3700321
loss is :  1.3698981
loss is :  1.3697642
loss is :  1.3696305
loss is :  1.3694967
loss is :  1.3693633
loss is :  1.3692298
loss is :  1.3690964
loss is :  1.3689634
loss is :  1.3688303
loss is :  1.3686975
loss is :  1.3685646
loss is :  1.368432
loss is :  1.3682996
loss is :  1.3681674
loss is :  1.3680352
loss is :  1.3679031
loss is :  1.3677711
loss is :  1.3676393
loss is :  1.3675077
loss is :  1.3673762
loss is :  1.3672451
loss is :  1.367114
loss is :  1.3669828
loss is :  1.3668522

loss is :  1.3364289
loss is :  1.336389
loss is :  1.3363494
loss is :  1.3363099
loss is :  1.3362705
loss is :  1.3362314
loss is :  1.3361923
loss is :  1.3361535
loss is :  1.3361148
loss is :  1.3360761
loss is :  1.3360378
loss is :  1.3359996
loss is :  1.3359616
loss is :  1.3359236
loss is :  1.3358858
loss is :  1.3358482
loss is :  1.3358107
loss is :  1.3357735
loss is :  1.3357363
loss is :  1.3356993
loss is :  1.3356624
loss is :  1.3356258
loss is :  1.3355892
loss is :  1.3355527
loss is :  1.3355166
loss is :  1.3354803
loss is :  1.3354445
loss is :  1.3354086
loss is :  1.3353729
loss is :  1.3353374
loss is :  1.3353019
loss is :  1.3352667
loss is :  1.3352315
loss is :  1.3351966
loss is :  1.3351618
loss is :  1.3351271
loss is :  1.3350927
loss is :  1.3350581
loss is :  1.3350238
loss is :  1.3349898
loss is :  1.3349557
loss is :  1.3349218
loss is :  1.334888
loss is :  1.3348545
loss is :  1.3348209
loss is :  1.3347875
loss is :  1.3347543
loss is :  1.33

loss is :  1.3267647
loss is :  1.3267568
loss is :  1.3267491
loss is :  1.3267412
loss is :  1.3267334
loss is :  1.3267256
loss is :  1.3267179
loss is :  1.3267101
loss is :  1.3267022
loss is :  1.3266947
loss is :  1.3266869
loss is :  1.3266791
loss is :  1.3266715
loss is :  1.3266639
loss is :  1.3266561
loss is :  1.3266485
loss is :  1.326641
loss is :  1.3266333
loss is :  1.326626
loss is :  1.3266182
loss is :  1.3266108
loss is :  1.3266032
loss is :  1.3265958
loss is :  1.3265882
loss is :  1.3265809
loss is :  1.3265733
loss is :  1.3265657
loss is :  1.3265584
loss is :  1.3265508
loss is :  1.3265436
loss is :  1.3265363
loss is :  1.3265289
loss is :  1.3265215
loss is :  1.3265142
loss is :  1.3265069
loss is :  1.3264996
loss is :  1.3264923
loss is :  1.326485
loss is :  1.3264778
loss is :  1.3264705
loss is :  1.3264633
loss is :  1.3264562
loss is :  1.326449
loss is :  1.3264418
loss is :  1.3264346
loss is :  1.3264275
loss is :  1.3264204
loss is :  1.3264

loss is :  1.3241233
loss is :  1.3241204
loss is :  1.3241175
loss is :  1.3241146
loss is :  1.3241117
loss is :  1.3241087
loss is :  1.3241056
loss is :  1.3241028
loss is :  1.3240998
loss is :  1.3240972
loss is :  1.324094
loss is :  1.3240911
loss is :  1.3240882
loss is :  1.3240852
loss is :  1.3240824
loss is :  1.3240795
loss is :  1.3240767
loss is :  1.3240739
loss is :  1.3240709
loss is :  1.324068
loss is :  1.3240652
loss is :  1.3240622
loss is :  1.3240595
loss is :  1.3240565
loss is :  1.3240538
loss is :  1.3240509
loss is :  1.324048
loss is :  1.3240453
loss is :  1.3240423
loss is :  1.3240396
loss is :  1.3240367
loss is :  1.3240339
loss is :  1.3240309
loss is :  1.3240281
loss is :  1.3240253
loss is :  1.3240227
loss is :  1.3240198
loss is :  1.324017
loss is :  1.3240141
loss is :  1.3240113
loss is :  1.3240086
loss is :  1.324006
loss is :  1.3240031
loss is :  1.3240004
loss is :  1.3239975
loss is :  1.3239946
loss is :  1.3239919
loss is :  1.32398

loss is :  1.3230054
loss is :  1.3230041
loss is :  1.3230025
loss is :  1.323001
loss is :  1.3229995
loss is :  1.322998
loss is :  1.3229964
loss is :  1.322995
loss is :  1.3229933
loss is :  1.3229917
loss is :  1.3229903
loss is :  1.3229889
loss is :  1.3229873
loss is :  1.3229858
loss is :  1.3229843
loss is :  1.3229829
loss is :  1.3229814
loss is :  1.3229799
loss is :  1.3229783
loss is :  1.3229768
loss is :  1.3229754
loss is :  1.322974
loss is :  1.3229723
loss is :  1.3229709
loss is :  1.3229694
loss is :  1.322968
loss is :  1.3229666
loss is :  1.3229649
loss is :  1.3229636
loss is :  1.322962
loss is :  1.3229606
loss is :  1.3229591
loss is :  1.3229578
loss is :  1.3229561
loss is :  1.3229548
loss is :  1.3229532
loss is :  1.3229517
loss is :  1.3229502
loss is :  1.3229488
loss is :  1.3229474
loss is :  1.3229457
loss is :  1.3229444
loss is :  1.322943
loss is :  1.3229415
loss is :  1.32294
loss is :  1.3229386
loss is :  1.3229371
loss is :  1.3229357
l

loss is :  1.322486
loss is :  1.3224852
loss is :  1.3224841
loss is :  1.3224832
loss is :  1.3224821
loss is :  1.3224812
loss is :  1.3224802
loss is :  1.3224791
loss is :  1.3224782
loss is :  1.3224771
loss is :  1.3224761
loss is :  1.3224751
loss is :  1.3224741
loss is :  1.3224732
loss is :  1.3224722
loss is :  1.3224713
loss is :  1.3224702
loss is :  1.3224691
loss is :  1.3224682
loss is :  1.3224671
loss is :  1.3224663
loss is :  1.3224651
loss is :  1.3224642
loss is :  1.3224632
loss is :  1.3224623
loss is :  1.3224612
loss is :  1.3224603
loss is :  1.3224592
loss is :  1.3224583
loss is :  1.3224573
loss is :  1.3224564
loss is :  1.3224554
loss is :  1.3224545
loss is :  1.3224534
loss is :  1.3224524
loss is :  1.3224515
loss is :  1.3224505
loss is :  1.3224497
loss is :  1.3224485
loss is :  1.3224477
loss is :  1.3224465
loss is :  1.3224458
loss is :  1.3224447
loss is :  1.3224437
loss is :  1.3224428
loss is :  1.3224418
loss is :  1.3224407
loss is :  1.3

loss is :  1.3220513
loss is :  1.3220508
loss is :  1.3220501
loss is :  1.3220493
loss is :  1.3220487
loss is :  1.3220482
loss is :  1.3220474
loss is :  1.3220468
loss is :  1.3220463
loss is :  1.3220456
loss is :  1.3220448
loss is :  1.3220443
loss is :  1.3220437
loss is :  1.322043
loss is :  1.3220422
loss is :  1.3220416
loss is :  1.322041
loss is :  1.3220403
loss is :  1.3220397
loss is :  1.3220391
loss is :  1.3220384
loss is :  1.3220377
loss is :  1.3220372
loss is :  1.3220365
loss is :  1.3220358
loss is :  1.3220352
loss is :  1.3220346
loss is :  1.3220339
loss is :  1.3220333
loss is :  1.3220327
loss is :  1.3220321
loss is :  1.3220316
loss is :  1.3220307
loss is :  1.3220301
loss is :  1.3220296
loss is :  1.322029
loss is :  1.3220282
loss is :  1.3220277
loss is :  1.3220271
loss is :  1.3220263
loss is :  1.3220258
loss is :  1.3220252
loss is :  1.3220243
loss is :  1.3220237
loss is :  1.3220232
loss is :  1.3220226
loss is :  1.322022
loss is :  1.3220

loss is :  1.3217525
loss is :  1.3217522
loss is :  1.3217517
loss is :  1.3217512
loss is :  1.3217508
loss is :  1.3217503
loss is :  1.3217499
loss is :  1.3217496
loss is :  1.3217491
loss is :  1.3217486
loss is :  1.3217481
loss is :  1.3217478
loss is :  1.3217473
loss is :  1.3217467
loss is :  1.3217463
loss is :  1.321746
loss is :  1.3217455
loss is :  1.321745
loss is :  1.3217446
loss is :  1.3217442
loss is :  1.3217437
loss is :  1.3217434
loss is :  1.3217428
loss is :  1.3217424
loss is :  1.321742
loss is :  1.3217415
loss is :  1.321741
loss is :  1.3217405
loss is :  1.3217403
loss is :  1.3217398
loss is :  1.3217393
loss is :  1.3217388
loss is :  1.3217384
loss is :  1.321738
loss is :  1.3217375
loss is :  1.3217372
loss is :  1.3217367
loss is :  1.3217363
loss is :  1.3217357
loss is :  1.3217353
loss is :  1.321735
loss is :  1.3217345
loss is :  1.3217341
loss is :  1.3217336
loss is :  1.3217332
loss is :  1.3217326
loss is :  1.3217324
loss is :  1.321731

loss is :  1.3215369
loss is :  1.3215365
loss is :  1.3215363
loss is :  1.3215361
loss is :  1.3215357
loss is :  1.3215353
loss is :  1.3215349
loss is :  1.3215346
loss is :  1.3215344
loss is :  1.3215342
loss is :  1.3215338
loss is :  1.3215334
loss is :  1.321533
loss is :  1.3215327
loss is :  1.3215325
loss is :  1.3215321
loss is :  1.3215318
loss is :  1.3215314
loss is :  1.3215312
loss is :  1.3215309
loss is :  1.3215306
loss is :  1.3215303
loss is :  1.3215299
loss is :  1.3215296
loss is :  1.3215292
loss is :  1.3215289
loss is :  1.3215287
loss is :  1.3215283
loss is :  1.321528
loss is :  1.3215277
loss is :  1.3215275
loss is :  1.321527
loss is :  1.3215268
loss is :  1.3215263
loss is :  1.321526
loss is :  1.3215258
loss is :  1.3215255
loss is :  1.3215252
loss is :  1.3215249
loss is :  1.3215245
loss is :  1.3215243
loss is :  1.3215238
loss is :  1.3215237
loss is :  1.3215232
loss is :  1.3215228
loss is :  1.3215227
loss is :  1.3215225
loss is :  1.3215

loss is :  1.3214209
loss is :  1.3214206
loss is :  1.3214202
loss is :  1.3214198
loss is :  1.3214198
loss is :  1.3214195
loss is :  1.3214192
loss is :  1.3214191
loss is :  1.3214188
loss is :  1.3214184
loss is :  1.3214182
loss is :  1.3214179
loss is :  1.3214178
loss is :  1.3214175
loss is :  1.3214173
loss is :  1.3214167
loss is :  1.3214165
loss is :  1.3214164
loss is :  1.321416
loss is :  1.3214159
loss is :  1.3214157
loss is :  1.3214154
loss is :  1.3214151
loss is :  1.3214147
loss is :  1.3214146
loss is :  1.3214144
loss is :  1.321414
loss is :  1.3214139
loss is :  1.3214135
loss is :  1.3214132
loss is :  1.3214129
loss is :  1.3214127
loss is :  1.3214124
loss is :  1.3214122
loss is :  1.321412
loss is :  1.3214117
loss is :  1.3214115
loss is :  1.3214113
loss is :  1.3214109
loss is :  1.3214107
loss is :  1.3214104
loss is :  1.3214101
loss is :  1.3214098
loss is :  1.3214096
loss is :  1.3214093
loss is :  1.3214091
loss is :  1.3214089
loss is :  1.321

loss is :  1.3213195
loss is :  1.3213195
loss is :  1.3213191
loss is :  1.321319
loss is :  1.3213187
loss is :  1.3213185
loss is :  1.3213183
loss is :  1.321318
loss is :  1.3213179
loss is :  1.3213178
loss is :  1.3213174
loss is :  1.3213173
loss is :  1.3213168
loss is :  1.3213167
loss is :  1.3213166
loss is :  1.3213164
loss is :  1.3213161
loss is :  1.3213159
loss is :  1.3213156
loss is :  1.3213155
loss is :  1.3213152
loss is :  1.3213149
loss is :  1.3213148
loss is :  1.3213147
loss is :  1.3213145
loss is :  1.3213143
loss is :  1.321314
loss is :  1.3213137
loss is :  1.3213135
loss is :  1.3213134
loss is :  1.3213131
loss is :  1.3213129
loss is :  1.3213128
loss is :  1.3213125
loss is :  1.3213124
loss is :  1.3213121
loss is :  1.3213118
loss is :  1.3213117
loss is :  1.3213115
loss is :  1.3213112
loss is :  1.321311
loss is :  1.3213109
loss is :  1.3213105
loss is :  1.3213103
loss is :  1.32131
loss is :  1.3213099
loss is :  1.3213098
loss is :  1.321309

loss is :  1.3212124
loss is :  1.321212
loss is :  1.3212119
loss is :  1.3212118
loss is :  1.3212117
loss is :  1.3212115
loss is :  1.3212113
loss is :  1.3212112
loss is :  1.321211
loss is :  1.3212107
loss is :  1.3212106
loss is :  1.3212104
loss is :  1.3212103
loss is :  1.32121
loss is :  1.3212099
loss is :  1.3212098
loss is :  1.3212098
loss is :  1.3212095
loss is :  1.3212093
loss is :  1.3212091
loss is :  1.321209
loss is :  1.3212087
loss is :  1.3212085
loss is :  1.3212084
loss is :  1.3212081
loss is :  1.321208
loss is :  1.321208
loss is :  1.3212079
loss is :  1.3212075
loss is :  1.3212074
loss is :  1.3212072
loss is :  1.321207
loss is :  1.3212068
loss is :  1.3212067
loss is :  1.3212066
loss is :  1.3212063
loss is :  1.3212062
loss is :  1.3212061
loss is :  1.3212059
loss is :  1.3212056
loss is :  1.3212055
loss is :  1.3212054
loss is :  1.3212054
loss is :  1.3212051
loss is :  1.3212049
loss is :  1.3212047
loss is :  1.3212044
loss is :  1.3212043


loss is :  1.3211459
loss is :  1.3211458
loss is :  1.3211455
loss is :  1.3211454
loss is :  1.3211453
loss is :  1.3211452
loss is :  1.321145
loss is :  1.321145
loss is :  1.3211448
loss is :  1.3211447
loss is :  1.3211446
loss is :  1.3211443
loss is :  1.3211442
loss is :  1.321144
loss is :  1.3211439
loss is :  1.3211436
loss is :  1.3211435
loss is :  1.3211434
loss is :  1.3211433
loss is :  1.3211432
loss is :  1.321143
loss is :  1.3211429
loss is :  1.3211428
loss is :  1.3211426
loss is :  1.3211426
loss is :  1.3211423
loss is :  1.3211421
loss is :  1.321142
loss is :  1.3211418
loss is :  1.3211418
loss is :  1.3211416
loss is :  1.3211412
loss is :  1.3211412
loss is :  1.3211411
loss is :  1.3211411
loss is :  1.3211409
loss is :  1.3211408
loss is :  1.3211408
loss is :  1.3211404
loss is :  1.3211404
loss is :  1.32114
loss is :  1.32114
loss is :  1.3211398
loss is :  1.3211397
loss is :  1.3211396
loss is :  1.3211393
loss is :  1.3211393
loss is :  1.3211392
l

loss is :  1.3210913
loss is :  1.3210913
loss is :  1.321091
loss is :  1.3210909
loss is :  1.3210907
loss is :  1.3210905
loss is :  1.3210905
loss is :  1.3210903
loss is :  1.3210902
loss is :  1.3210901
loss is :  1.32109
loss is :  1.3210899
loss is :  1.3210897
loss is :  1.3210896
loss is :  1.3210896
loss is :  1.3210894
loss is :  1.3210894
loss is :  1.321089
loss is :  1.321089
loss is :  1.3210889
loss is :  1.3210888
loss is :  1.3210886
loss is :  1.3210884
loss is :  1.3210883
loss is :  1.3210883
loss is :  1.3210881
loss is :  1.321088
loss is :  1.3210878
loss is :  1.3210878
loss is :  1.3210876
loss is :  1.3210876
loss is :  1.3210874
loss is :  1.3210874
loss is :  1.3210872
loss is :  1.3210871
loss is :  1.3210869
loss is :  1.3210868
loss is :  1.3210866
loss is :  1.3210866
loss is :  1.3210864
loss is :  1.3210862
loss is :  1.3210862
loss is :  1.321086
loss is :  1.3210859
loss is :  1.3210859
loss is :  1.3210857
loss is :  1.3210856
loss is :  1.3210855

loss is :  1.3210441
loss is :  1.321044
loss is :  1.3210438
loss is :  1.3210437
loss is :  1.3210436
loss is :  1.3210435
loss is :  1.3210435
loss is :  1.3210433
loss is :  1.3210431
loss is :  1.321043
loss is :  1.321043
loss is :  1.3210429
loss is :  1.3210428
loss is :  1.3210425
loss is :  1.3210425
loss is :  1.3210424
loss is :  1.3210422
loss is :  1.3210422
loss is :  1.3210421
loss is :  1.321042
loss is :  1.321042
loss is :  1.3210418
loss is :  1.3210417
loss is :  1.3210416
loss is :  1.3210415
loss is :  1.3210413
loss is :  1.3210413
loss is :  1.3210411
loss is :  1.3210411
loss is :  1.3210407
loss is :  1.3210407
loss is :  1.3210406
loss is :  1.3210405
loss is :  1.3210404
loss is :  1.3210403
loss is :  1.3210402
loss is :  1.3210402
loss is :  1.3210402
loss is :  1.32104
loss is :  1.3210399
loss is :  1.3210398
loss is :  1.3210396
loss is :  1.3210396
loss is :  1.3210393
loss is :  1.3210393
loss is :  1.3210391
loss is :  1.3210391
loss is :  1.321039


loss is :  1.3209888
loss is :  1.3209888
loss is :  1.3209887
loss is :  1.3209887
loss is :  1.3209884
loss is :  1.3209884
loss is :  1.3209883
loss is :  1.3209882
loss is :  1.3209882
loss is :  1.320988
loss is :  1.3209878
loss is :  1.3209878
loss is :  1.3209878
loss is :  1.3209876
loss is :  1.3209876
loss is :  1.3209876
loss is :  1.3209875
loss is :  1.3209872
loss is :  1.320987
loss is :  1.3209871
loss is :  1.320987
loss is :  1.320987
loss is :  1.3209867
loss is :  1.3209867
loss is :  1.3209866
loss is :  1.3209866
loss is :  1.3209864
loss is :  1.3209864
loss is :  1.3209863
loss is :  1.3209862
loss is :  1.3209862
loss is :  1.320986
loss is :  1.3209858
loss is :  1.3209857
loss is :  1.3209857
loss is :  1.3209856
loss is :  1.3209856
loss is :  1.3209853
loss is :  1.3209853
loss is :  1.3209852
loss is :  1.3209851
loss is :  1.3209851
loss is :  1.3209851
loss is :  1.3209848
loss is :  1.3209848
loss is :  1.3209848
loss is :  1.3209847
loss is :  1.32098

loss is :  1.320942
loss is :  1.320942
loss is :  1.320942
loss is :  1.3209418
loss is :  1.3209418
loss is :  1.3209417
loss is :  1.3209416
loss is :  1.3209414
loss is :  1.3209413
loss is :  1.3209414
loss is :  1.3209412
loss is :  1.3209411
loss is :  1.320941
loss is :  1.3209411
loss is :  1.320941
loss is :  1.320941
loss is :  1.3209409
loss is :  1.3209409
loss is :  1.3209407
loss is :  1.3209407
loss is :  1.3209406
loss is :  1.3209405
loss is :  1.3209404
loss is :  1.3209403
loss is :  1.3209401
loss is :  1.32094
loss is :  1.32094
loss is :  1.32094
loss is :  1.3209399
loss is :  1.3209398
loss is :  1.3209398
loss is :  1.3209397
loss is :  1.3209397
loss is :  1.3209395
loss is :  1.3209395
loss is :  1.3209393
loss is :  1.3209393
loss is :  1.3209391
loss is :  1.3209391
loss is :  1.3209391
loss is :  1.3209388
loss is :  1.3209388
loss is :  1.3209388
loss is :  1.3209387
loss is :  1.3209386
loss is :  1.3209386
loss is :  1.3209385
loss is :  1.3209383
loss

loss is :  1.3209054
loss is :  1.3209052
loss is :  1.3209052
loss is :  1.3209051
loss is :  1.320905
loss is :  1.3209049
loss is :  1.3209049
loss is :  1.3209049
loss is :  1.3209047
loss is :  1.3209047
loss is :  1.3209047
loss is :  1.3209046
loss is :  1.3209046
loss is :  1.3209045
loss is :  1.3209044
loss is :  1.3209044
loss is :  1.3209043
loss is :  1.3209041
loss is :  1.3209041
loss is :  1.320904
loss is :  1.320904
loss is :  1.3209038
loss is :  1.3209038
loss is :  1.3209037
loss is :  1.3209037
loss is :  1.3209035
loss is :  1.3209034
loss is :  1.3209034
loss is :  1.3209034
loss is :  1.3209032
loss is :  1.3209032
loss is :  1.3209032
loss is :  1.3209032
loss is :  1.320903
loss is :  1.320903
loss is :  1.320903
loss is :  1.3209028
loss is :  1.3209028
loss is :  1.3209028
loss is :  1.3209027
loss is :  1.3209025
loss is :  1.3209025
loss is :  1.3209025
loss is :  1.3209023
loss is :  1.3209022
loss is :  1.3209022
loss is :  1.3209022
loss is :  1.320902

loss is :  1.320871
loss is :  1.3208709
loss is :  1.320871
loss is :  1.3208708
loss is :  1.3208708
loss is :  1.3208708
loss is :  1.3208705
loss is :  1.3208705
loss is :  1.3208704
loss is :  1.3208704
loss is :  1.3208704
loss is :  1.3208703
loss is :  1.3208703
loss is :  1.3208703
loss is :  1.3208702
loss is :  1.32087
loss is :  1.32087
loss is :  1.32087
loss is :  1.3208699
loss is :  1.3208699
loss is :  1.3208698
loss is :  1.3208698
loss is :  1.3208697
loss is :  1.3208696
loss is :  1.3208696
loss is :  1.3208696
loss is :  1.3208694
loss is :  1.3208692
loss is :  1.3208692
loss is :  1.3208691
loss is :  1.3208691
loss is :  1.320869
loss is :  1.3208691
loss is :  1.320869
loss is :  1.3208688
loss is :  1.3208688
loss is :  1.3208687
loss is :  1.3208687
loss is :  1.3208686
loss is :  1.3208685
loss is :  1.3208685
loss is :  1.3208685
loss is :  1.3208685
loss is :  1.3208685
loss is :  1.3208685
loss is :  1.3208684
loss is :  1.3208684
loss is :  1.3208683
lo

In [40]:
print(sess.run(W1))
print('----------')
print(sess.run(b1))
print('----------')

[[-0.37793124 -0.6129675   1.4897666   1.8057561  -0.8507164 ]
 [ 0.5259207   1.0436023  -1.4264289   0.20767358  0.28914234]
 [-0.17349388  1.4196011   0.23122992  1.2217362   0.1555665 ]
 [-1.2719496  -2.0159404  -1.5964833   1.0980406  -1.3962483 ]
 [ 0.17836711  0.5267014  -0.3485979  -2.2964165  -0.48384693]
 [ 0.46928418  2.4696007  -0.52355814  1.2969537   0.5508474 ]
 [ 1.3994625  -2.4168603   0.75447094 -1.8052255   0.35447213]]
----------
[-1.7764674   2.2405734   0.04281462 -0.4572555   0.6595358 ]
----------


In [41]:
vectors = sess.run(W1 + b1)

In [42]:
vectors

array([[-2.1543987 ,  1.6276059 ,  1.5325812 ,  1.3485006 , -0.19118059],
       [-1.2505467 ,  3.2841759 , -1.3836143 , -0.24958193,  0.94867814],
       [-1.9499613 ,  3.6601744 ,  0.27404454,  0.7644807 ,  0.81510234],
       [-3.048417  ,  0.22463298, -1.5536687 ,  0.6407851 , -0.7367125 ],
       [-1.5981003 ,  2.7672749 , -0.3057833 , -2.7536721 ,  0.1756889 ],
       [-1.3071833 ,  4.710174  , -0.48074353,  0.8396982 ,  1.2103832 ],
       [-0.37700498, -0.17628694,  0.79728556, -2.262481  ,  1.0140079 ]],
      dtype=float32)

In [43]:
word2int

{'royal': 0, 'king': 1, 'he': 2, 'the': 3, 'queen': 4, 'she': 5, 'is': 6}

In [44]:
print(vectors[ word2int['queen'] ])

[-1.5981003  2.7672749 -0.3057833 -2.7536721  0.1756889]


In [45]:
model = tf.keras.models.Sequential()

In [46]:
model.add(tf.keras.layers.Dense(7, input_shape=(None, 7), activation = 'relu'))

In [47]:
model.add(tf.keras.layers.Dense(7, activation = 'softmax'))

In [48]:
model.compile(optimizer='adam', loss =  tf.keras.losses.categorical_crossentropy, metrics=["accuracy"])

In [49]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, None, 7)           56        
_________________________________________________________________
dense_1 (Dense)              (None, None, 7)           56        
Total params: 112
Trainable params: 112
Non-trainable params: 0
_________________________________________________________________


In [50]:
x_train = x_train.reshape(34, 1, 7 )

In [51]:
x_train

array([[[0., 0., 1., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 1., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0.]],

       [[0., 0., 0., 1., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0., 0., 0.]],

       [[1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 0., 1.]],



In [52]:
y_train = y_train.reshape(34, 1, 7)

In [53]:
model.fit(x=x_train, y=y_train, batch_size = 2, epochs=100)

Train on 34 samples
Epoch 1/100
34/34 [==============================] - 0s 382us/sample - loss: 1.8560 - acc: 0.2059
Epoch 2/100
34/34 [==============================] - 0s 412us/sample - loss: 1.8447 - acc: 0.1765
Epoch 3/100
34/34 [==============================] - 0s 441us/sample - loss: 1.8352 - acc: 0.1765
Epoch 4/100
34/34 [==============================] - 0s 471us/sample - loss: 1.8261 - acc: 0.1765
Epoch 5/100
34/34 [==============================] - 0s 471us/sample - loss: 1.8169 - acc: 0.1765
Epoch 6/100
34/34 [==============================] - 0s 500us/sample - loss: 1.8080 - acc: 0.1765
Epoch 7/100
34/34 [==============================] - 0s 441us/sample - loss: 1.7998 - acc: 0.1471
Epoch 8/100
34/34 [==============================] - 0s 441us/sample - loss: 1.7916 - acc: 0.1765
Epoch 9/100
34/34 [==============================] - 0s 442us/sample - loss: 1.7835 - acc: 0.1765
Epoch 10/100
34/34 [==============================] - 0s 441us/sample - loss: 1.7769 - acc: 0.1765

34/34 [==============================] - 0s 441us/sample - loss: 1.5505 - acc: 0.3235
Epoch 84/100
34/34 [==============================] - 0s 470us/sample - loss: 1.5486 - acc: 0.3235
Epoch 85/100
34/34 [==============================] - 0s 529us/sample - loss: 1.5467 - acc: 0.3529
Epoch 86/100
34/34 [==============================] - 0s 559us/sample - loss: 1.5462 - acc: 0.3235
Epoch 87/100
34/34 [==============================] - 0s 323us/sample - loss: 1.5439 - acc: 0.3529
Epoch 88/100
34/34 [==============================] - 0s 383us/sample - loss: 1.5421 - acc: 0.3529
Epoch 89/100
34/34 [==============================] - 0s 353us/sample - loss: 1.5412 - acc: 0.3529
Epoch 90/100
34/34 [==============================] - 0s 442us/sample - loss: 1.5395 - acc: 0.3529
Epoch 91/100
34/34 [==============================] - 0s 471us/sample - loss: 1.5383 - acc: 0.3529
Epoch 92/100
34/34 [==============================] - 0s 441us/sample - loss: 1.5371 - acc: 0.3529
Epoch 93/100
34/34 [===

In [54]:
model.get_layer('dense_7').get_weights()

ValueError: No such layer: dense_7.